//
// Generated by Bluespec Compiler, version 2023.07-10-gda4b93f1 (build da4b93f1)
//
// On Wed Oct 18 09:10:02 CST 2023
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 unused
// RST_N                          I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module lab(CLK,
	   RST_N);
  input  CLK;
  input  RST_N;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    $display("Hello World!");
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd0),
	     $unsigned(2'd0),
	     $unsigned(2'd0),
	     1'd0);
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd0),
	     $unsigned(2'd0),
	     $unsigned(2'd1),
	     1'd0);
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd0),
	     $unsigned(2'd1),
	     $unsigned(2'd0),
	     1'd1);
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd0),
	     $unsigned(2'd1),
	     $unsigned(2'd1),
	     1'd1);
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd1),
	     $unsigned(2'd0),
	     $unsigned(2'd0),
	     1'd0);
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd1),
	     $unsigned(2'd0),
	     $unsigned(2'd1),
	     1'd1);
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd1),
	     $unsigned(2'd1),
	     $unsigned(2'd0),
	     1'd0);
    $display("multiplelexer(%b,%b,%b)=%b",
	     $unsigned(2'd1),
	     $unsigned(2'd1),
	     $unsigned(2'd1),
	     1'd1);
    $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // lab

